### DISCUSSION TITLE
nb-cli 脚本/插件简易开发教程

### DISCUSSION THREAD

**Discussion by MingxuanGame** [nonebot/discussions#298] [经验]
# 1. 概览

伴随着 nb-cli 1.0 的发布，nb-cli 支持了脚本、插件系统，这允许我们拓展 bot 或 nb-cli 的功能，例如快捷的 bot 管理

## nb-cli 1.0 更新了什么

根据 [开源之夏 - 暑期 2022](https://nonebot.dev/ospp-2022.html)（nonebot/nb-cli#35，nonebot/nb-cli#38）以及 [Commit 历史](https://github.com/nonebot/nb-cli/compare/v0.6.7...v1.0.0)，目前更新了如下等功能：

- 用户模板（bootstrap）/开发者模板（simple）
- 自动冷重启
- i18n
- 虚拟环境支持
- 无入口文件启动支持
- **CLI 脚本/插件支持**

本教程着重讲解 `CLI 脚本/插件支持`，其他内容请看[文档](https://cli.nonebot.dev)

## 选择 `脚本` 还是 `插件`

虽然脚本和插件都可以扩展 nb-cli，但是有以下差异点

|      | 运行环境    | 适用范围 | 运行前操作               | 运行时操作       | 依赖               |
| ---- | ----------- | -------- | ------------------------ | ---------------- | ------------------ |
| 脚本 | 用户环境    | 当前项目 | 注册适配器、加载插件[^1] | 直接运行对应函数 |  NoneBot2 |
| 插件 | nb-cli 环境 | 全局     | 执行安装函数             |                  | 无

- 如果你只是想管理当前项目，那么脚本足矣
- 如果你是想全局扩展 nb-cli，那么使用插件

## 注册你的脚本/插件

插件/脚本使用 [`entry_points`](https://packaging.python.org/en/latest/specifications/entry-points/) 机制，将下面内容写进你的 `pyproject.toml` 来注册插件/脚本：

- [PEP 621](https://peps.python.org/pep-0621/) 格式（适用于 setuptools/pdm）:

  ```toml
  # 脚本
  [project.entry-points.nb_scripts]
  # entry 为直接运行的函数
  my_script = "awesome_bot.module:entry"

  # 插件
  [project.entry-points.nb]
  # entry 函数为安装函数，用于在 nb-cli 运行前执行部分操作，比如注册命令
  my_plugin = "cli_plugin.plugin:entry"
  ```

- [Poetry](https://python-poetry.org/docs/pyproject/#plugins) 格式：

  ```toml
  # 注释同上
  [tool.poetry.plugins.nb_scripts]
  my_script = "awesome_bot.module:entry"

  [tool.poetry.plugins.nb]
  my_plugin = "cli_plugin.plugin:entry"
  ```

## Hello World!

```py
def entry():
    print("Hello World!")
```

> **Warning**
>
> 插件需要和 nb-cli 安装到同一环境

脚本输出：

```shell
$ nb my_script
01-14 15:57:54 [SUCCESS] nonebot | NoneBot is initializing...
01-14 15:57:54 [INFO] nonebot | Current Env: prod
<string>:14: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.
Hello World!
```

插件输出：

```text
$ nb
Hello World!
d8b   db  .d88b.  d8b   db d88888b d8888b.  .d88b.  d888888b
888o  88 .8P  Y8. 888o  88 88'     88  `8D .8P  Y8. `~~88~~'
88V8o 88 88    88 88V8o 88 88ooooo 88oooY' 88    88    88
88 V8o88 88    88 88 V8o88 88~~~~~ 88~~~b. 88    88    88
88  V888 `8b  d8' 88  V888 88.     88   8D `8b  d8'    88
VP   V8P  `Y88P'  VP   V8P Y88888P Y8888P'  `Y88P'     YP
[?] What do you want to do?
❯ Create a NoneBot project.
  Run the bot in current folder
  Generate entry file of your bot
  Manage bot plugins.
  Manage bot adapters.
  Manage bot driver.
```

> **Note**
>
> 你应该注意到插件的 `Hello World!` 打印在 Logo 前面，这也说明在 nb-cli 运行前会执行插件的安装函数

[^1]:[`run_script.jinja`](https://github.com/nonebot/nb-cli/blob/master/nb_cli/template/scripts/script/run_script.py.jinja) -> [`_prepare.py.jinja`](https://github.com/nonebot/nb-cli/blob/master/nb_cli/template/scripts/project/_prepare.py.jinja)
