### DISCUSSION TITLE
用requests去探查机器人运行状态，没有反应，请指导下写法

### DISCUSSION THREAD

**Discussion by vincentlin7** [nonebot/discussions#307] [问答]
```python
url = "http://127.0.0.1:5000/api/v11/status"
try:
    response = requests.get(url)
    print(response)
    if response.status_code == 200:
        print("Nonebot is running and responding.")
    else:
        print("Nonebot is running but not responding.")
except requests.exceptions.RequestException:
    print("Nonebot is not running.")
```

**Comment by yanyongyu** [comment]
你是否在nonebot上添加了这个路由

**Reply by vincentlin7** [reply]
我是从chatgpt 上面找到了上面的写法，小白
go-cqhttps config.yml 设置了这个
```yaml
  - ws-reverse:
      # 反向WS Universal 地址
      # 注意 设置了此项地址后下面两项将会被忽略
      universal: ws://127.0.0.1:5000/onebot/v11/ws
      # 反向WS API 地址
      api: ws://your_websocket_api.server
      # 反向WS Event 地址
      event: ws://your_websocket_event.server
      # 重连间隔 单位毫秒
      reconnect-interval: 3000
      middlewares:
        <<: *default # 引用默认中间件
```
启动是这样的
```
01-30 10:30:57 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
01-30 10:30:57 [SUCCESS] nonebot | NoneBot is initializing...
01-30 10:30:57 [INFO] nonebot | Current Env: prod
01-30 10:30:58 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
01-30 10:30:58 [SUCCESS] nonebot | Running NoneBot...
01-30 10:30:58 [INFO] logging | Started server process [6896]
01-30 10:30:58 [INFO] logging | Waiting for application startup.
01-30 10:30:58 [INFO] nonebot_plugin_apscheduler | Scheduler Started
01-30 10:30:58 [INFO] logging | Application startup complete.
01-30 10:30:58 [INFO] logging | Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
01-30 10:30:59 [INFO] logging | ('127.0.0.1', 49331) - "WebSocket /onebot/v11/ws" [accepted]
01-30 10:30:59 [INFO] nonebot | OneBot V11 | Bot *** connected
01-30 10:30:59 [INFO] logging | connection open
```
