### DISCUSSION TITLE
链接反向WebSocket Universal服务器时出错

### DISCUSSION THREAD

**Discussion by ACQKLDXG** [nonebot/discussions#333] [问答] [answered]
go-cqhttp日志

```
[2023-03-01 21:22:36] [INFO]: 开始诊断网络情况
[2023-03-01 21:22:39] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:8080/onebot/v11/ws
[2023-03-01 21:22:39] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/onebot/v11/ws 时出现错误: websocket: bad handshake

```
nonebot日志

```
03-01 21:22:30 [SUCCESS] nonebot | NoneBot is initializing...
03-01 21:22:30 [INFO] nonebot | Current Env: prod
03-01 21:22:33 [SUCCESS] nonebot | Succeeded to import "demo"
03-01 21:22:33 [SUCCESS] nonebot | Running NoneBot...
03-01 21:22:34 [INFO] uvicorn | Started server process [5748]
03-01 21:22:34 [INFO] uvicorn | Waiting for application startup.
03-01 21:22:34 [INFO] uvicorn | Application startup complete.
03-01 21:22:34 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
03-01 21:22:36 [INFO] uvicorn | ('127.0.0.1', 60334) - "WebSocket /onebot/v11/ws" 403
03-01 21:22:36 [INFO] websockets | connection failed (403 Forbidden)
03-01 21:22:36 [INFO] websockets | connection closed
```

bot.py文件

```
import nonebot


nonebot.init()

driver = nonebot.get_driver()

nonebot.load_plugins("plugins")
nonebot.load_from_toml("pyproject.toml")

if __name__ == "__main__":
    nonebot.run()
```

.env.prod文件
'
```
DRIVER=~fastapi
HOST=0.0.0.0  # 配置 NoneBot2 监听的 IP/主机名
PORT=8080  # 配置 NoneBot2 监听的端口
COMMAND_START=["/"]  # 配置命令起始字符
COMMAND_SEP=["."]  # 配置命令分割字符
```
'
config.yml文件
```
servers:
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器

  - http: # HTTP 通信设置
      address: 127.0.0.1:5700 # HTTP监听地址
      timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
      long-polling:   # 长轮询拓展
        enabled: false       # 是否开启
        max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
      middlewares:
        <<: *default # 引用默认中间件
       #post:           # 反向HTTP POST地址列表
         #- url: 'http://127.0.0.1:8000/'                # 地址
           #secret: ''             # 密钥
           #max-retries: 3         # 最大重试，0 时禁用
           #retries-interval: 1500 # 重试时间，单位毫秒，0 时立即
      #- url: http://127.0.0.1:5701/ # 地址
      #  secret: ''                  # 密钥
      #  max-retries: 10             # 最大重试，0 时禁用
      #  retries-interval: 1000      # 重试时间，单位毫秒，0 时立即
  # 反向WS设置
  - ws-reverse:
      # 反向WS Universal 地址
      # 注意 设置了此项地址后下面两项将会被忽略
      universal: ws://127.0.0.1:8080/onebot/v11/ws
      # 反向WS API 地址
      api: ws://your_websocket_api.server
      # 反向WS Event 地址
      event: ws://your_websocket_event.server
      # 重连间隔 单位毫秒
      reconnect-interval: 3000
      middlewares:
        <<: *default # 引用默认中间件
```
听群友说是没有安装noebot11适配器，但我重新安装了，还是没有用
