### DISCUSSION TITLE
使用 nb plugin install 安装的插件似乎无法生效？

### DISCUSSION THREAD

**Discussion by ninthseason** [nonebot/discussions#81] [问答] [answered]
例如安装服务器状态查看插件：

`nb plugin install 服务器状态查看`

能够正常下载，其在pyproject.tmol中[nonebot.plugins]节点处添加了条目：

```tmol
[nonebot]
[nonebot.plugins]
plugins = ["nonebot_plugin_status"]
plugin_dirs = []
```

`bot.py`中亦是正常加载该文件：

```python
nonebot.load_builtin_plugins("echo")

# Please DO NOT modify this file unless you know what you are doing!
# As an alternative, you should use command `nb` or modify `pyproject.toml` to load plugins
nonebot.load_from_toml("pyproject.toml")
```

但使用`nb run`启动后并未加载该插件：

```bash
01-13 14:09:56 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
01-13 14:09:56 [SUCCESS] nonebot | Succeeded to import "nonebot.plugins.echo"
01-13 14:09:56 [SUCCESS] nonebot | Running NoneBot...
01-13 14:09:56 [DEBUG] nonebot | Loaded adapters: OneBot V11
```

所有使用`nb plugin install`安装的插件皆是如此。

**Comment by yanyongyu** [comment]
> ```tmol
> [nonebot]
> [nonebot.plugins]
> plugins = ["nonebot_plugin_status"]
> plugin_dirs = []
> ```

你可以尝试修改为 `[tool.nonebot]`，或者删除第一行的 `[nonebot]`

**Reply by ninthseason** [reply]
pyproject.tmol的完整内容是这样的：

```tmol
[tool.poetry]
name = "Beta01"
version = "0.1.0"
description = "Beta01"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.3"
nonebot2 = "^2.0.0-beta.1"

[tool.poetry.dev-dependencies]
nb-cli = "^0.6.0"

[tool.nonebot]
plugins = []
plugin_dirs = ["src/plugins"]

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[nonebot]
[nonebot.plugins]
plugins = ["nonebot_plugin_status"]
plugin_dirs = []
```

其中

```tmol
[nonebot]
[nonebot.plugins]
plugins = ["nonebot_plugin_status"]
plugin_dirs = []
```

新建项目时没有，运行`nb plugin install`后才出现的。

---

按照你的解决方案均未成功：

将`[nonebot.plugins]`改为`[tool.nonebot]`，`nb run`报错如下。

```bash
tomlkit.exceptions.KeyAlreadyPresent: Key "nonebot" already exists.
```

删去`[nonebot]`能运行，但仍加载不到：

```bash
01-13 14:54:08 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
01-13 14:54:08 [SUCCESS] nonebot | Succeeded to import "nonebot.plugins.echo"
01-13 14:54:08 [SUCCESS] nonebot | Running NoneBot...
01-13 14:54:08 [DEBUG] nonebot | Loaded adapters: OneBot V11
```

把`"nonebot_plugin_status"`放到上面的`[tool.nonebot]`中也是不行的，会报大量的错。

**Comment by mnixry** [comment, marked as answer]
```toml
[tool.poetry]
name = "Beta01"
version = "0.1.0"
description = "Beta01"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.3"
nonebot2 = "^2.0.0-beta.1"

[tool.poetry.dev-dependencies]
nb-cli = "^0.6.0"

[tool.nonebot]
plugins = ["nonebot_plugin_status"]
plugin_dirs = ["src/plugins"]

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

这应该是你`pyproject.toml`配置文件的正确格式，有大量报错是正常的，因为`nonebot_plugin_status`尚未适配2.0.0-beta1版本

/cc @yanyongyu
